---
# panos_facts.yml - Gather data about a PAN-OS device.
#
# Description
# ===========
#
# Uses the 'panos_facts' module to gather a subset of system data about a PAN-OS device.
#
# This playbook requires connection details for the device to be specified in the variables 'ip_address', 'username',
# and 'password'.  These may be defined as host variables (see `host_vars/firewall.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# panos_facts - https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_facts.html
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory panos_facts_system.yml

- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: '{{ device }}'
        gather_subset: ['system']

